

spring:
  application:
    name: client-service

server:
  port: ${PORT:8081}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
#      defaultZone: http://admin:admin123@localhost:8761/eureka/
    registry-fetch-interval-seconds: 30