
server:
  port: 8000

spring:
  application:
    name: insta-media-service

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB # allow only images for now
      max-request-size: 20MB

file:
  upload-dir: /Users/nag/insta-clone-images/
  path:
    prefix: /images



